### PR TITLE
Enhacements

### PR DESCRIPTION
**Pull request by domdinicola**

### CODE REVIEW

**Comment by srugano** [comment]
@domdinicola  Running it locally goes well enough for me.  image .
It seems the DEFAULT_FILE_STORAGE is removed in 5.1.  https://github.com/jazzband/django-avatar/issues/245

**Comment by domdinicola** [comment]
Dear @srugano not sure why you mention DEFAULT_FILE_STORAGE?
Can you try to help to understand why the build is not passing?

**Comment by domdinicola** [comment]
what was the blocker? @srugano

**Comment by srugano** [comment]
In Django 42+ they removed django51warning. Pytest.ini was referring to it.

**Pull request merged**
